//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ParticipantUser struct {
	ID           *int64
	Name         *string
	Email        *string
	Address      *string
	Organizer    *bool
	Participates *bool
	Accepted     *bool
	EventID      *int64
	UserID       *int64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	UserName     *string
	UserEmail    *string
	UserImageURL *string
}
