//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Product struct {
	ID           int64 `sql:"primary_key"`
	Title        string
	Description  *string
	ProductKey   string
	ImageURL     string
	TotalReviews int32
	Rating       float32
	Price        string
	Currency     CurrencyType
	URL          string
	CategoryID   *int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ProductTs    *string
	Origin       string
}
