//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Wish struct {
	ID            int64 `sql:"primary_key"`
	UserID        int64
	ParticipantID int64
	ProductID     *int64
	EventID       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Quantity      int32
}
