// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: link.sql

package database

import (
	"context"
	"time"
)

const createLink = `-- name: CreateLink :one
INSERT INTO "link" (
    code,
    expiration_date,
    event_id
) VALUES (
    $1, $2, $3
) RETURNING id, code, expiration_date, event_id, created_at, updated_at
`

type CreateLinkParams struct {
	Code           string    `db:"code" json:"code"`
	ExpirationDate time.Time `db:"expiration_date" json:"expirationDate"`
	EventID        int64     `db:"event_id" json:"eventId"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.queryRow(ctx, q.createLinkStmt, createLink, arg.Code, arg.ExpirationDate, arg.EventID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ExpirationDate,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
