// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CategoryUrl string         `db:"category_url" json:"categoryUrl"`
}

type Draw struct {
	ID        int64     `db:"id" json:"id"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	DrawerID  int64     `db:"drawer_id" json:"drawerId"`
	DraweeID  int64     `db:"drawee_id" json:"draweeId"`
	EventID   int64     `db:"event_id" json:"eventId"`
}

type Event struct {
	ID                int64          `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Description       sql.NullString `db:"description" json:"description"`
	Budget            string         `db:"budget" json:"budget"`
	InvitationMessage string         `db:"invitation_message" json:"invitationMessage"`
	CreatedAt         time.Time      `db:"created_at" json:"createdAt"`
	DrawAt            time.Time      `db:"draw_at" json:"drawAt"`
	CloseAt           time.Time      `db:"close_at" json:"closeAt"`
}

type Link struct {
	ID             int64     `db:"id" json:"id"`
	Code           string    `db:"code" json:"code"`
	CreatedAt      time.Time `db:"created_at" json:"createdAt"`
	ExpirationDate time.Time `db:"expiration_date" json:"expirationDate"`
	EventID        int64     `db:"event_id" json:"eventId"`
}

type Participant struct {
	ID           int64        `db:"id" json:"id"`
	Name         string       `db:"name" json:"name"`
	Email        string       `db:"email" json:"email"`
	Address      string       `db:"address" json:"address"`
	Organizer    sql.NullBool `db:"organizer" json:"organizer"`
	Participates sql.NullBool `db:"participates" json:"participates"`
	Accepted     sql.NullBool `db:"accepted" json:"accepted"`
	EventID      int64        `db:"event_id" json:"eventId"`
	UserID       int64        `db:"user_id" json:"userId"`
}

type Product struct {
	ID           int64          `db:"id" json:"id"`
	Title        string         `db:"title" json:"title"`
	Description  sql.NullString `db:"description" json:"description"`
	ProductKey   string         `db:"product_key" json:"productKey"`
	ImageUrl     string         `db:"image_url" json:"imageUrl"`
	TotalReviews int32          `db:"total_reviews" json:"totalReviews"`
	Rating       float32        `db:"rating" json:"rating"`
	Price        string         `db:"price" json:"price"`
	Currency     string         `db:"currency" json:"currency"`
	Modified     time.Time      `db:"modified" json:"modified"`
	Website      string         `db:"website" json:"website"`
	CategoryID   int64          `db:"category_id" json:"categoryId"`
	ProductTs    interface{}    `db:"product_ts" json:"productTs"`
}

type User struct {
	ID       int64          `db:"id" json:"id"`
	Name     string         `db:"name" json:"name"`
	Email    string         `db:"email" json:"email"`
	ImageUrl string         `db:"image_url" json:"imageUrl"`
	Phone    sql.NullString `db:"phone" json:"phone"`
	Admin    sql.NullBool   `db:"admin" json:"admin"`
	Active   sql.NullBool   `db:"active" json:"active"`
}

type Wish struct {
	ID            int64     `db:"id" json:"id"`
	CreatedAt     time.Time `db:"created_at" json:"createdAt"`
	UserID        int64     `db:"user_id" json:"userId"`
	ParticipantID int64     `db:"participant_id" json:"participantId"`
	ProductID     int64     `db:"product_id" json:"productId"`
	EventID       int64     `db:"event_id" json:"eventId"`
}
