// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: participant.sql

package database

import (
	"context"
	"database/sql"
)

const acceptEventInvite = `-- name: AcceptEventInvite :one
UPDATE "participant"
SET
    "accepted" = TRUE,
    "user_id" = $1,
    "updated_at" = now()
WHERE 
    "email" = $2
        AND
    "event_id" = $3
RETURNING id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at
`

type AcceptEventInviteParams struct {
	UserID  sql.NullInt64 `db:"user_id" json:"userId"`
	Email   string        `db:"email" json:"email"`
	EventID int64         `db:"event_id" json:"eventId"`
}

func (q *Queries) AcceptEventInvite(ctx context.Context, arg AcceptEventInviteParams) (Participant, error) {
	row := q.queryRow(ctx, q.acceptEventInviteStmt, acceptEventInvite, arg.UserID, arg.Email, arg.EventID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO "participant" (
    "name",
    "email",
    "address",
    "organizer",
    "participates",
    "accepted",
    "event_id",
    "user_id"
) VALUES (
    $1, $2, $7, $3, $4, $5, $6, $8
)
RETURNING id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at
`

type CreateParticipantParams struct {
	Name         string         `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	Organizer    bool           `db:"organizer" json:"organizer"`
	Participates bool           `db:"participates" json:"participates"`
	Accepted     bool           `db:"accepted" json:"accepted"`
	EventID      int64          `db:"event_id" json:"eventId"`
	Address      sql.NullString `db:"address" json:"address"`
	UserID       sql.NullInt64  `db:"user_id" json:"userId"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.queryRow(ctx, q.createParticipantStmt, createParticipant,
		arg.Name,
		arg.Email,
		arg.Organizer,
		arg.Participates,
		arg.Accepted,
		arg.EventID,
		arg.Address,
		arg.UserID,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineEventInvite = `-- name: DeclineEventInvite :one
DELETE FROM "participant"
WHERE 
    "email" = $1
        AND
    "event_id" = $2
        AND
    "accepted" = FALSE
RETURNING id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at
`

type DeclineEventInviteParams struct {
	Email   string `db:"email" json:"email"`
	EventID int64  `db:"event_id" json:"eventId"`
}

func (q *Queries) DeclineEventInvite(ctx context.Context, arg DeclineEventInviteParams) (Participant, error) {
	row := q.queryRow(ctx, q.declineEventInviteStmt, declineEventInvite, arg.Email, arg.EventID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParticipantByIdAndEventId = `-- name: DeleteParticipantByIdAndEventId :one
DELETE FROM "participant"
WHERE "event_id" = $1 AND "id" = $2
RETURNING id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at
`

type DeleteParticipantByIdAndEventIdParams struct {
	EventID       int64 `db:"event_id" json:"eventId"`
	ParticipantID int64 `db:"participant_id" json:"participantId"`
}

func (q *Queries) DeleteParticipantByIdAndEventId(ctx context.Context, arg DeleteParticipantByIdAndEventIdParams) (Participant, error) {
	row := q.queryRow(ctx, q.deleteParticipantByIdAndEventIdStmt, deleteParticipantByIdAndEventId, arg.EventID, arg.ParticipantID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findParticipantFromEventIdAndUser = `-- name: FindParticipantFromEventIdAndUser :one
SELECT id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at FROM "participant"
WHERE "event_id" = $1 AND "user_id" = $2
`

type FindParticipantFromEventIdAndUserParams struct {
	EventID int64         `db:"event_id" json:"eventId"`
	UserID  sql.NullInt64 `db:"user_id" json:"userId"`
}

func (q *Queries) FindParticipantFromEventIdAndUser(ctx context.Context, arg FindParticipantFromEventIdAndUserParams) (Participant, error) {
	row := q.queryRow(ctx, q.findParticipantFromEventIdAndUserStmt, findParticipantFromEventIdAndUser, arg.EventID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findParticipantUserWithId = `-- name: FindParticipantUserWithId :one
SELECT
    participant_user.id, participant_user.name, participant_user.email, participant_user.address, participant_user.organizer, participant_user.participates, participant_user.accepted, participant_user.event_id, participant_user.user_id, participant_user.created_at, participant_user.updated_at, participant_user.user_name, participant_user.user_email, participant_user.user_image_url,
    event.id, event.name, event.description, event.budget, event.invitation_message, event.draw_at, event.close_at, event.created_at, event.updated_at
FROM "participant_user"
JOIN "event" ON "event"."id" = "participant_user"."event_id"
WHERE "participant_user"."id" = $1
`

type FindParticipantUserWithIdRow struct {
	ParticipantUser ParticipantUser `db:"participant_user" json:"participantUser"`
	Event           Event           `db:"event" json:"event"`
}

func (q *Queries) FindParticipantUserWithId(ctx context.Context, id int64) (FindParticipantUserWithIdRow, error) {
	row := q.queryRow(ctx, q.findParticipantUserWithIdStmt, findParticipantUserWithId, id)
	var i FindParticipantUserWithIdRow
	err := row.Scan(
		&i.ParticipantUser.ID,
		&i.ParticipantUser.Name,
		&i.ParticipantUser.Email,
		&i.ParticipantUser.Address,
		&i.ParticipantUser.Organizer,
		&i.ParticipantUser.Participates,
		&i.ParticipantUser.Accepted,
		&i.ParticipantUser.EventID,
		&i.ParticipantUser.UserID,
		&i.ParticipantUser.CreatedAt,
		&i.ParticipantUser.UpdatedAt,
		&i.ParticipantUser.UserName,
		&i.ParticipantUser.UserEmail,
		&i.ParticipantUser.UserImageUrl,
		&i.Event.ID,
		&i.Event.Name,
		&i.Event.Description,
		&i.Event.Budget,
		&i.Event.InvitationMessage,
		&i.Event.DrawAt,
		&i.Event.CloseAt,
		&i.Event.CreatedAt,
		&i.Event.UpdatedAt,
	)
	return i, err
}

const findParticipantWithIdAndEventId = `-- name: FindParticipantWithIdAndEventId :one
SELECT id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at FROM "participant"
WHERE "event_id" = $1 AND "id" = $2
`

type FindParticipantWithIdAndEventIdParams struct {
	EventID       int64 `db:"event_id" json:"eventId"`
	ParticipantID int64 `db:"participant_id" json:"participantId"`
}

func (q *Queries) FindParticipantWithIdAndEventId(ctx context.Context, arg FindParticipantWithIdAndEventIdParams) (Participant, error) {
	row := q.queryRow(ctx, q.findParticipantWithIdAndEventIdStmt, findParticipantWithIdAndEventId, arg.EventID, arg.ParticipantID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :one
UPDATE "participant"
SET
    "organizer" = COALESCE($2, "organizer"),
    "participates" = COALESCE($3, "participates"),
    "updated_at" = now()
WHERE "event_id" = $1 AND "id" = $4
RETURNING id, name, email, address, organizer, participates, accepted, event_id, user_id, created_at, updated_at
`

type UpdateParticipantStatusParams struct {
	EventID       int64        `db:"event_id" json:"eventId"`
	Organizer     sql.NullBool `db:"organizer" json:"organizer"`
	Participates  sql.NullBool `db:"participates" json:"participates"`
	ParticipantID int64        `db:"participant_id" json:"participantId"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (Participant, error) {
	row := q.queryRow(ctx, q.updateParticipantStatusStmt, updateParticipantStatus,
		arg.EventID,
		arg.Organizer,
		arg.Participates,
		arg.ParticipantID,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.Organizer,
		&i.Participates,
		&i.Accepted,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
