// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: wish.sql

package database

import (
	"context"
	"database/sql"
)

const createWish = `-- name: CreateWish :one
INSERT INTO wish (
    user_id,
    participant_id,
    product_id,
    event_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, now(), now()
) RETURNING id, user_id, participant_id, product_id, event_id, created_at, updated_at
`

type CreateWishParams struct {
	UserID        int64         `db:"user_id" json:"userId"`
	ParticipantID int64         `db:"participant_id" json:"participantId"`
	ProductID     sql.NullInt64 `db:"product_id" json:"productId"`
	EventID       int64         `db:"event_id" json:"eventId"`
}

func (q *Queries) CreateWish(ctx context.Context, arg CreateWishParams) (Wish, error) {
	row := q.queryRow(ctx, q.createWishStmt, createWish,
		arg.UserID,
		arg.ParticipantID,
		arg.ProductID,
		arg.EventID,
	)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParticipantID,
		&i.ProductID,
		&i.EventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
