name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: password

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: create database
      run: 

    - name: build
      run: make build

    - name: run tests
      env:
        TEST_DB: postgres
      run: make test